# NGC 5
### Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

#### Import Library

In [1]:
import numpy as np # import lib numpy

In [5]:
vector1=np.array([[[23,50],[7,12],  ##Buat tensor dengan nama vector1
                   [57,67],[99,43],
                   [75,21],[57,12],
                   [87,26],[18,84]]])
vector1

array([[[23, 50],
        [ 7, 12],
        [57, 67],
        [99, 43],
        [75, 21],
        [57, 12],
        [87, 26],
        [18, 84]]])


### Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

In [9]:
A=np.array([[23,50,19], #buat matriks dengan nama A
            [7,12,109],
            [57,67,98]])
A@np.array([[17], ##Lakukan perkalian matriks A dengan matriks sesuai soal
            [22],
            [19]])

array([[1852],
       [2454],
       [4305]])

### Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$

Buat matriks

In [10]:
matriks=np.array([[23,50,19],
                  [7,12,109],
                  [57,67,98]])

Transpose

In [11]:
matriks.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

Determinan

In [12]:
np.linalg.det(matriks)

131344.0000000002

Invers

In [13]:
np.linalg.inv(matriks)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])